version: '3.5'
services:
  contentdb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ruben_content
      MYSQL_PASSWORD: 12345_content
      MYSQL_DATABASE: content
    restart: always
    ports:
      - 54350:3306
    volumes:
      - content_data:/var/lib/mysql

  userdb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ruben_user
      MYSQL_PASSWORD: 12345_user
      MYSQL_DATABASE: user
    restart: always
    ports:
      - 54351:3306
    volumes:
      - ./db-init/db-init-user.sql.sql:/docker-entrypoint-initdb.d/init.sql
      - user_data:/var/lib/mysql

  notificationdb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ruben_notification
      MYSQL_PASSWORD: 12345_notification
      MYSQL_DATABASE: notification
    restart: always
    ports:
      - 54352:3306
    volumes:
      - notification_data:/var/lib/mysql

  adminer:
    image: adminer
    platform: linux/amd64
    restart: always
    ports:
      - 18080:8080

volumes:
  content_data:
  user_data:
  notification_data: